# Build configuration for code generators
targets:
  $default:
    builders:
      # Isar generator - only process model files
      isar_community_generator:
        enabled: true
        generate_for:
          include:
            - lib/model/**
            - lib/sync/models/**
            - lib/sync/repository/**
            - lib/lan_sync/model/**
      
      # Riverpod generator - process provider files
      riverpod_generator:
        enabled: true
        generate_for:
          include:
            - lib/providers/**
            - lib/api/**
            - lib/sync/sync_service.dart
