-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- 1. Resource Metadata Table
-- Stores the original content and metadata of the crawled resource.
CREATE TABLE IF NOT EXISTS resource_metadata (
    id UUID PRIMARY KEY, -- UUIDv7 is recommended for application layer generation
    user_id VARCHAR(64) NOT NULL, -- Multi-tenant isolation
    original_url TEXT NOT NULL,
    title TEXT,
    content_markdown TEXT, -- Content fetched by Jina
    ai_summary TEXT, -- Summary generated by AI
    ai_tags JSONB, -- Tags generated by AI
    process_status VARCHAR(20) DEFAULT 'PENDING', -- PENDING, CRAWLED, EMBEDDED, FAILED
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_resource_user_id ON resource_metadata(user_id);
CREATE INDEX IF NOT EXISTS idx_resource_url ON resource_metadata(original_url);

-- 2. Resource Embeddings Table
-- Stores vector embeddings for RAG.
CREATE TABLE IF NOT EXISTS resource_embeddings (
    id UUID PRIMARY KEY,
    resource_id UUID NOT NULL REFERENCES resource_metadata(id) ON DELETE CASCADE,
    segment_content TEXT, -- The text chunk
    embedding vector(1536), -- OpenAI/DashScope compatible dimension
    metadata JSONB, -- Extra info like page number, chunk index
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_embedding_resource_id ON resource_embeddings(resource_id);
-- HNSW index for fast similarity search
CREATE INDEX IF NOT EXISTS idx_embedding_vector ON resource_embeddings USING hnsw (embedding vector_cosine_ops);

-- 3. Chat Sessions Table
-- Stores conversation sessions related to a specific resource.
CREATE TABLE IF NOT EXISTS chat_sessions (
    id UUID PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    resource_id UUID NOT NULL REFERENCES resource_metadata(id) ON DELETE CASCADE,
    topic VARCHAR(255),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_session_user_resource ON chat_sessions(user_id, resource_id);

-- 4. Chat Messages Table
-- Stores individual messages within a session.
CREATE TABLE IF NOT EXISTS chat_messages (
    id UUID PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL, -- USER, ASSISTANT
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_message_session_created ON chat_messages(session_id, created_at);
